
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-client
  template:
    metadata:
      labels:
        app: todo-client
    spec:
      containers:
        - name: client
          image: sandy7461/todoapp_client:latest
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: todo-client-svc
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo-client
  ports:
    - port: 80
      targetPort: 80
