apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: todo-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: ""   # no host restriction; use bare IP
      http:
        paths:
          # Frontend: route "/" to client service
          - path: /(.*)?
            pathType: Prefix
            backend:
              service:
                name: todo-client-svc
                port:
                  number: 80

          # Backend: route "/api" to server service
          - path: /api(/.*)?
            pathType: Prefix
            backend:
              service:
                name: todo-server-svc
                port:
                  number: 5000
