apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: todo-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: ""
      http:
        paths:

          # Frontend: serve all at "/"
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-client-svc
                port:
                  number: 80

          # Backend: API path
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-server-svc
                port:
                  number: 5000
